### ISSUE TITLE
Expose docker daemon tcp port to allow commands via ssh tunnel

### ISSUE THREAD

**Issue by rocketraman** [docker/for-azure#1]
The docker manager instance runs on a unix socket. In order to allow commands to this manager via an ssh tunnel, should it also expose a listener on a tcp port?

That way, one can run commands from a remote docker client, and use a remote docker-compose instance for creating services.

**Comment by nathanleclaire** [comment]
You could tunnel to the remote daemon socket over SSH today ([detailed here](https://docs.docker.com/docker-for-azure/deploy/#/connecting-via-ssh)) if desired if you have a recent enough version of OpenSSH.

We'd like to have this type of remote access functionality more tightly integrated into Docker for Mac / Docker for Windows in the future, but that's a bit nebulously defined at the moment -- stay tuned.

**Comment by rocketraman** [comment]
> You could tunnel to the remote daemon socket over SSH today (detailed here) if desired if you have a recent enough version of OpenSSH

Ah, nice! Just learned something.

NOTE: In the docs, it says you have to append the domain to ssh to the worker nodes from the manager. I've found that is not necessary on Azure -- you just do `ssh swarm-worker000001` and it works fine without the domain.

**Comment by nathanleclaire** [comment]
> NOTE: In the docs, it says you have to append the domain to ssh to the worker nodes from the manager. I've found that is not necessary on Azure -- you just do ssh swarm-worker000001 and it works fine without the domain.

Oh fun, maybe we over-estimated what's needed here, but that hadn't worked last time I tried it.
