### ISSUE TITLE
Network interfaces are not being cleared

### ISSUE THREAD

**Issue by markvr** [docker/for-azure#11]
### Expected behavior

Hi, whilst deploying a swarm update, the update failed and the following error was available: 

```
starting container failed: container 48f94450916b0511b7066c5e735b7c13ed5ecd7bbcd748783b04ff4c2435af30: endpoint create on GW Network failed: failed to create endpoint gateway_48f94450916b on network docker_gwbridge: adding interface veth3a88d2a to bridge docker_gwbridge failed: exchange full"
```

Counting the network interfaces with `ifconfig | grep HWaddr | wc -l` , there were 1030 interfaces.  I'm running a small test swarm of about 10 replicas in total across 4 nodes, so this is a bit excessive!

Rebooting each node from the Azure portal cleared the interfaces.

### Actual behavior

Not to have so many network interfaces.

### Information

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance
diagnostics session: 1488816054-57qpScTMNJqWtP4VdM4RdcoooisvSGmn

### Steps to reproduce the behavior

I think this has slowly occurred over a few weeks of usage, so its' hard to reproduce immediately, but I wanted to put this out there in case other people are experiencing problems.  I'll monitor the interface count over time and see if it reoccurs.

**Comment by ddebroy** [comment]
Closing since we did not get this repro.
