### ISSUE TITLE
Add templates to repo

### ISSUE THREAD

**Issue by lazzurs** [docker/for-azure#21]
The templates can currently be downloaded and used with Azure but it would be useful to have them in this GitHub repo so pull requests can be submitted rather than just issues.

**Comment by friism** [comment]
Thanks for opening this issue. We're not currently accepting contributions to the templates. Is there a particular change or improvement that you're looking for?

**Comment by lazzurs** [comment]
Thanks for the response. My other issue #20 is a good example, if the template was here I could submit a pull request to make a change to add an IPv6 address to the frontend load balancer.

On a more general note, nothing in Docker would be possible without the open source ecosystem so it just seemed strange that this repo would be here but not have the template in the repo.

**Comment by ddebroy** [comment]
Closing the issue since we do not plan to open source the templates in the near future for contributions.
