### ISSUE TITLE
Default logging backend and doc guidance 

### ISSUE THREAD

**Issue by rocketraman** [docker/for-azure#3]
Logging is configured to use `syslog`. This means `docker logs` does not work. And `docker service logs <servicename>` just hangs without producing any output.

Please provide some guidance in the documentation about how to manage logging within Azure and swarm mode. According to https://github.com/docker/docker/issues/24812 this should generally be working, but perhaps not with the syslog configured default. The default setup should probably allow `docker service logs` to work correctly, and then people can modify their logging setup as desired from there.

**Comment by FrenchBen** [comment]
This is actually documented within the Docker docs, please see:
https://docs.docker.com/docker-for-azure/faqs/#/where-are-my-container-logs

**Comment by rocketraman** [comment]
Somehow I missed that, thanks.
