### ISSUE TITLE
Additional Resources without Tags

### ISSUE THREAD

**Issue by ryandanthony** [docker/for-azure#30]
### Expected behavior
I should be able to add additional resources to the Azure Template that don't have tags. 

### Actual behavior
When I add a resource that doesn't have any tags on it, the swarm will come up without having cloudstor:azure plugin installed, because it is not able to determine the channel tag.

This may depend on the order that the resources are created, or just the order that the resources are listed in the resource group. 

The error message I am getting is:
```
Traceback (most recent call last):
  File "/usr/bin/aztags.py", line 47, in <module>
    main()
  File "/usr/bin/aztags.py", line 44, in main
    print(get_tag_value(resource_client, args.tag_name))
  File "/usr/bin/aztags.py", line 23, in get_tag_value
    if tag_name in item.tags:
TypeError: argument of type 'NoneType' is not iterable
 Skip cloudstor installation
```
### Information

aztags.py has a function/method:
```
def get_tag_value(resource_client, tag_name):
    for item in resource_client.resource_groups.list_resources(RG_NAME):
        if tag_name in item.tags:
            return item.tags[tag_name]
    raise KeyError(tag_name + " Not found in any resource")
```
get_tag_value of aztags.py should check for null tags (please don't trust my phython skills):
```
def get_tag_value(resource_client, tag_name):
    for item in resource_client.resource_groups.list_resources(RG_NAME):
        if not (item.tags is None) and tag_name in item.tags:
            return item.tags[tag_name]
    raise KeyError(tag_name + " Not found in any resource")
```

**Comment by ddebroy** [comment]
Nice catch! This should be fixed in our next release where we no longer look at the channel tag in Azure to determine whether to install cloudstor. We always install cloudstor irrespective of the channel.
