### ISSUE TITLE
Stable channel deployment missing latest stable version

### ISSUE THREAD

**Issue by jalberto** [docker/for-azure#32]
### Expected behavior

After deployment I expect to have latest stable version (17.06.2-ce)

### Actual behavior

version deployed is 17.06.0-ce

### Information

swarm-manager000001:~$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

### Steps to reproduce the behavior

  1. deploy using azure portal
  2. run docker version

**Comment by ddebroy** [comment]
https://download.docker.com/azure/stable/Docker.tmpl was just updated by @FrenchBen.

**Comment by jalberto** [comment]
thanks!
