### ISSUE TITLE
Scaling swarm-worker-vmss virtual machine scale set takes down the stack

### ISSUE THREAD

**Issue by msalvadores** [docker/for-azure#49]
### Expected behavior

I want to add more worker nodes and scale up one of my stack services. I would expect my stack to keep working while scaling up workers.

### Actual behavior

When swarm-worker-vmss virtual machine scale starts resizing I loose connectivity to all the stack endpoints.

### Steps to reproduce the behavior

  1. Login into cloud.docker.com
  2. Using Azure as a provider create a 1 Manager (VM DS4)  and 4 Worker (VM DS3) swarm.
  3. Once it is provisioned deploy a simple stack that exposes an HTTP endpoint.
  4. Create a HTTP client that loops over calling one of the HTTP services. Leave it running forever.
  5. Login into Portal Azure, navigate to the Swarm Resource Group, select the `swarm-worker-vmss` and scale to 10 workers.
  6. The HTTP client in 4 dies with connections errors.
  7. Retrying makes the client fail for a couple of minutes until the swarm services recover.

**Comment by FrenchBen** [comment]
@msalvadores if I understand this properly, you're losing connectivity when using the Docker Cloud provided swarm connection?
If that's the case I would open up a thread within the Docker Cloud forums:
https://forums.docker.com/c/docker-cloud

**Comment by msalvadores** [comment]
> if I understand this properly, you're losing connectivity when using the Docker Cloud provided swarm connection?

Yes that is correct @FrenchBen 

I did post in that forum a few days ago but no answer there so far.

https://forums.docker.com/t/scaling-swarm-worker-vmss-virtual-machine-scale-set-takes-down-the-stack/45097

**Comment by FrenchBen** [comment]
Since this is linked to Docker Cloud's solution I will defer to that thread instead of this issue.
