### ISSUE TITLE
Home directory still requires sudo to write

### ISSUE THREAD

**Issue by rocketraman** [docker/for-azure#5]
According to https://docs.docker.com/docker-for-azure/release-notes/ the latest version should no longer require sudo to write to the home directory. It still does, as it is owned by root with 755 permissions:

```
swarm-manager000000:~$ ls -al
total 12
drwxr-xr-x    3 root     root          4096 Jan 24 15:52 .
drwxr-xr-x    3 docker   docker        4096 Jan 24 15:52 ..
drwx------    2 docker   docker        4096 Jan 24 15:52 .ssh
```

**Comment by nathanleclaire** [comment]
Yeah this is known issue (permissions mistake) and we intend to fix in the next release.   Thanks!
