### ISSUE TITLE
Docker-CE-Basic Cannot Be Purchased due to validation errors

### ISSUE THREAD

**Issue by gregatpeakblockchain** [docker/for-azure#50]
### Expected behavior

- Successful Azure Deployment

### Actual behavior

- Error message when clicking "Purchase" of the following:

`{"telemetryId":"bcf038e5-fb71-4311-8bbd-da6ed8c42f8c","bladeInstanceId":"Blade_2d169c75bd024e6a82928663cc106edb_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"MarketplacePurchaseEligibilityFailed","message":"Marketplace purchase eligibilty check returned errors. See inner errors for details. ","details":[{"code":"BadRequest","message":"Offer with PublisherId: docker, OfferId: docker-ce-basic cannot be purchased due to validation errors. See details for more information.[{\"Offer with PublisherId: docker and OfferId: docker-ce-basic not found. If this offer has been created recently, please allow upto 30 minutes for this offer to be available for Purchase. If error persists, contact support.\":\"StoreApi\"}]"},{"code":"BadRequest","message":"Offer with PublisherId: docker, OfferId: docker-ce-basic cannot be purchased due to validation errors. See details for more information.[{\"Offer with PublisherId: docker and OfferId: docker-ce-basic not found. If this offer has been created recently, please allow upto 30 minutes for this offer to be available for Purchase. If error persists, contact support.\":\"StoreApi\"}]"}]}`

### Information

  - Tried multiple VM sizes, resource groups, etc to validate that it was nothing on my specific account
  - Someone else just posted this question to the Azure forum [here](https://social.msdn.microsoft.com/Forums/en-US/2f4ef59c-84b7-44cb-b2d9-5dd0ca9c99ca/dockercebasic-not-found?forum=DataMarket) 

### Steps to reproduce the behavior

  1. Navigate to the Docker-CE Template on Azure
  2. Fill out required fields and click "Purchase"

**Comment by FrenchBen** [comment]
Thanks for opening the issue - It looks like the VM image is still pending within Azure, causing this error. 
It's usually a 24hr process, but seems to be hung up on something on the Azure side. I'll update this ticket when I heard back from their support team.

**Comment by uberwrensch** [comment]
@FrenchBen, no update from Azure side?

**Comment by adijes** [comment]
Any updates regarding this issue? I am getting the same error when trying to deploy docker azure template

**Comment by FrenchBen** [comment]
All images should now be published. Going to qa both deployments, but they should now deploy without any issue

**Comment by sentinelt** [comment]
Works now, thanks

**Comment by gregatpeakblockchain** [comment]
Confirmed. Closing issue - thank you!
