### ISSUE TITLE
Missing upgrade of stable channel to 17.12-ce

### ISSUE THREAD

**Issue by djeeg** [docker/for-azure#51]
Hi, wanting to upgrade a 17.09-ce swarm, as having network issues (eg Address already in use)

### Expected behavior

upgrade.sh 17.12.0-ce-azure1
or
upgrade.sh 17.12.1-ce-azure1

### Actual behavior

I see that there is a 17.12 release on the stable channel
https://docs.docker.com/docker-for-azure/release-notes/#stable-channel

However there doesnt seem to be a 17.12 tag in docker4x/upgrade-azure
https://hub.docker.com/r/docker4x/upgrade-azure/tags/

Actually the naming format for the upgrade tags seems to have changed
https://docs.docker.com/docker-for-azure/upgrade/#upgrading

Was: docker4x/upgrade-azure:17.06.1-ce-azure1
Now: docker4x/upgrade-azure:18.02-latest

Or are we waiting for https://github.com/docker/docker-ce/releases/tag/v17.12.1-ce

**Comment by FrenchBen** [comment]
@djeeg yes, the updated 17.12.1 is what we were waiting for - It will be built this week with hopefully a release early next. 
I'll make sure to check on the upgrade scripts as well, but the new format is what you're looking for, aka `$ upgrade.sh 17.12.1-ce-azure1`

**Comment by djeeg** [comment]
Closing as up to 18.03 now

**Comment by khell** [comment]
What's the status of this? I'm also trying to upgrade from 17.09.0-ce, but there are still no valid upgrade images that match the format on the upgrading page: https://hub.docker.com/r/docker4x/upgrade-azure/tags/

```
swarm-manager000001:~$ upgrade.sh 18.03.0-ce-azure1
Error response from daemon: manifest for docker4x/upgrade-azure:18.03.0-ce-azure1 not found
Upgrade target 18.03.0-ce-azure1 not found. Please confirm 18.03.0-ce-azure1 has been released by Docker.
swarm-manager000001:~$ upgrade.sh 17.12.1-ce-azure1
Error response from daemon: manifest for docker4x/upgrade-azure:17.12.1-ce-azure1 not found
Upgrade target 17.12.1-ce-azure1 not found. Please confirm 17.12.1-ce-azure1 has been released by Docker.
```
