### ISSUE TITLE
rm cloudstor plugin with alias not clean

### ISSUE THREAD

**Issue by djeeg** [docker/for-azure#57]
### Expected behavior

No docker engine errors after removing cloudstor plugin

### Actual behavior

Errors from syslog
```
cannot stat /mnt/cloudstor/OLDVOLUMENAME: stat /mnt/cloudstor/OLDVOLUMENAME input/output error name=NEWVOLUMENAME
could not fetch metadata: cannot read metadata: open /mnt/cloudstor/cloudstor-metadata/OLDVOLUMENAME: no such file or directory
```

### Information / Steps

swarm 17.12.0, 3 nodes, MANAGER, WORKER1, WORKER2

Initially added an aliased cloudstor plugin to MANAGER only (mistakenly)

```
MANAGER$ docker plugin install --alias cloudstor:sharedlogs \
  --grant-all-permissions docker4x/cloudstor:17.12.0-ce-azure1  \
  AZURE_STORAGE_ACCOUNT="sharedlogs"
```
  
Created a volume on the MANAGER only

`MANAGER$ docker volume create --name sharedlogs_vollogs --driver "cloudstor:sharedlogs"`

Deployed multiple stacks with multiple services referencing this volume

```
volumes:
  sharedlogs_vollogs:
    external: true #ignored in stacks
```
	
When auditing swarm, saw docker engine had created missing volumes as local

```
MANAGER$ docker volume ls
sharedlogs_vollogs cloudstor:sharedlogs
WORKER1$ docker volume ls
sharedlogs_vollogs local
WORKER2$ docker volume ls
sharedlogs_vollogs local
```

Needed to correct the configuration by removing all stacks, then removing all volumes
(watch out, didnt realise that this also purges the azure directory)

```
MANAGER$ docker volume rm sharedlogs_vollogs
WORKER1$ docker volume rm sharedlogs_vollogs
WORKER2$ docker volume rm sharedlogs_vollogs
```

No issues, then removed plugin from MANAGER

`MANAGER$ docker plugin rm cloudstor:sharedlogs`

Back to a clean swarm state I had hoped.

Add the plugin back to all nodes, with a NEW alias, SAME storage account
(maybe this not supported? always needs to be a brand new storage account? some azure metadata cached somewhere in docker land?)

```
MANAGER$ docker plugin install --alias cloudstor:betterlogs \
  --grant-all-permissions docker4x/cloudstor:17.12.0-ce-azure1  \
  AZURE_STORAGE_ACCOUNT="sharedlogs"
  
WORKER1$ docker plugin install --alias cloudstor:betterlogs \
  --grant-all-permissions docker4x/cloudstor:17.12.0-ce-azure1  \
  AZURE_STORAGE_ACCOUNT="sharedlogs"
  
WORKER2$ docker plugin install --alias cloudstor:betterlogs \
  --grant-all-permissions docker4x/cloudstor:17.12.0-ce-azure1  \
  AZURE_STORAGE_ACCOUNT="sharedlogs"
```

Deployed a simple stack whose sole purpose is to provision the volume on each node

```
version: '3.4'
services:
  volumecontrol:
    image: busybox
    command: sleep 2073600
    volumes:
      - volsharedlog:/logs
    deploy:
      mode: global
volumes:
  volsharedlog:
    name: 'base_volsharedlog'
    driver: cloudstor:betterlogs
```
	
Other stacks can then reference this volume, and the cloudstor volume should have already been created on each node
(well still testing if it is guaranteed to be)

```
volumes:
  base_volsharedlog:
    external: true #ignored in stacks
```
	
All seems to be working correctly, logs get written to the azure storage account 

### The Error

Checking docker logs I get an error

`$MANAGER$ cat /var/log/syslog | grep error`

> Mar 13 02:47:42 moby root: time="2018-03-13T02:47:42Z" level=error msg="time=\"2018-03-13T02:47:42Z\" level=error msg=\"cannot stat /mnt/cloudstor/sharedlogs_vollogs: stat /mnt/cloudstor/sharedlogs_vollogs: input/output error\" name=\"base_volsharedlog\" operation=unmount " plugin=213cf06d0abc7209bc49042f5c2f<removed>

> Mar 13 03:05:08 moby root: time="2018-03-13T03:05:08Z" level=error msg="time=\"2018-03-13T03:05:08Z\" level=error msg=\"could not fetch metadata: cannot read metadata: open /mnt/cloudstor/cloudstor-metadata/sharedlogs_vollogs: no such file or directory\" name=\"sharedlogs_vollogs\" operation=get " plugin=71114008c2ae534b2be26f8fced4c2<removed>

This is odd because - the message references part of the old and part of the new volume/plugin
The old plugin/volume/directory seems to be hanging around
The plugin ID is the new plugin alias
I cant see the old plugin/volume with any of the commands

**Comment by FrenchBen** [comment]
If you don't deploy the CloudStor plugin from the get-go, then you have to go through the manual steps you mentioned, as explained here:
https://docs.docker.com/docker-for-azure/persistent-data-volumes/

To make the process easier (post deployment), we created a handy tool called `swarm-exec`:
https://docs.docker.com/docker-for-azure/deploy/#execute-docker-commands-in-all-swarm-nodes

Can you do a `docker volume ls` on all of the nodes, to confirm that the volume was actually created with the right volume name+driver?
The error that you're seeing is an invalid mapping of your old volume, with the use of the new volume name, aka `sharedlogs_vollogs` is to be used by `base_volsharedlog`

I'm guessing you're re-using the same naming convention after bad deployments, which causes some volume conflicts. I would rename them, to prevent any naming conflicts.

In your last volume declaration, you can actually be very verbose:
```
volumes:
  base_volsharedlog:
    name: 'base_volsharedlog'
    external: true
```

**Comment by djeeg** [comment]
> go through the manual steps

Yep this is what im doing

> handy tool called swarm-exec

Cool thats interesting, I assume though that this only works on existing nodes, if i auto scale it will have to add the plugin manually still.

Something like this hangs `swarm-exec docker ps` oh well

> confirm that the volume was actually created with the right volume name+driver

Yep they were (that swarm is gone now though)

> I would rename them, to prevent any naming conflicts.

Okay good to know, **be very careful with the naming**

Thanks for the tips!

**Comment by FrenchBen** [comment]
@djeeg the `swarm-exec` tool is more of a 1-shot task, then a command that will provide information back to the original issuer. 
That's why it's been highlighted as a way to execute a command on all nodes in the cluster, not a way to gather that information.
