### ISSUE TITLE
Restarted demoted manager does not rejoin the swarm

### ISSUE THREAD

**Issue by djeeg** [docker/for-azure#60]
### Expected behavior

Scale set instances can rejoin swarm after reboot

### Actual behavior

Node not joined

### Information

Start with 3 MANAGERS

```
 swarm-manager000003:~$ docker node ls
ID                            HOSTNAME              STATUS              AVAILABILITY        MANAGER STATUS
n4ox0f13dta     swarm-manager000000   Ready               Drain
i6kcjzg5wt8     swarm-manager000002   Ready               Active              Leader
isy1lqj6b17 *   swarm-manager000003   Ready               Active              Reachable
hwovd2ti366     swarm-worker000000    Ready               Active
lkym8b4dz0     swarm-worker000001    Ready               Active
```

`docker node update --availability drain swarm-manager000000`

Wait for tasks to transfer to other nodes

`docker node demote swarm-manager000000`

Restart in Azure

![image](https://user-images.githubusercontent.com/4269005/37580205-61ccb18a-2b3a-11e8-9f12-30718abc6596.png)

![image](https://user-images.githubusercontent.com/4269005/37580209-64ac66c0-2b3a-11e8-9b78-be682e5493f9.png)

Wait for reboot and raft
Instance does not rejoin the swarm

```
swarm-manager000003:~$ docker node ls
ID                            HOSTNAME              STATUS              AVAILABILITY        MANAGER STATUS
i6kcjzg5wt8     swarm-manager000002   Ready               Active              Leader
isy1lqj6b1r *   swarm-manager000003   Ready               Active              Reachable
hwovd2ti3     swarm-worker000000    Ready               Active
lkym8b4dz     swarm-worker000001    Ready               Active
```

Even though it has rebooted and can be connected to

```
swarm-manager000000:~$ docker node ls
Error response from daemon: This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this command on a manager node or promote the current node to a manager.
```

**Comment by djeeg** [comment]
Try to reimage - seems to get stuck at "deleting"

![image](https://user-images.githubusercontent.com/4269005/37583910-5f1182d4-2b4b-11e8-8fd0-4a22b8d94f0a.png)

![image](https://user-images.githubusercontent.com/4269005/37583918-61c853ae-2b4b-11e8-8e50-cae2a6274e7e.png)

![image](https://user-images.githubusercontent.com/4269005/37583919-638bfcae-2b4b-11e8-80b4-973b5104c4e8.png)

**Comment by FrenchBen** [comment]
Same as with the other clusters, you need to look at the `init` container logs to get a proper idea of what's going on and why it's not working as expected.

**Comment by djeeg** [comment]
Suspect duplicate https://github.com/docker/for-azure/issues/59
