### ISSUE TITLE
Newly provisioned swarm is not working as swarm is not initialized.

### ISSUE THREAD

**Issue by Praggie** [docker/for-azure#63]
I've tried to create a new swarm using the template from https://docs.docker.com/docker-for-azure/

### Expected behavior
A new swarm is created, and ready to use.
### Actual behavior
A new swarm got created, but the logical swarm didn't form. Swarm is not initialized.
### Information

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance

Docker-diagnose session ID:1525226669-Y96023yLhENYOd8EKFcrjzMXKGt7tc0h

### Steps to reproduce the behavior

1. Go to https://docs.docker.com/docker-for-azure/
2. Create a swarm (stable channel)
3. SSH into the swarm
4. issue docker node ls
5. You will get the following message Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

**Comment by FrenchBen** [comment]
@Praggie it looks like there are some issues with your setup, as the diagnostic upload didn't succeed. 
Could you provide the list of containers running on each manager?
You can join our community channel on Slack to provide private logs, for better debugging

**Comment by Praggie** [comment]
I have recreated the swarm and same issue appeared. Here is the docker-diagnose output:
swarm-manager000000:~$ docker-diagnose
OK hostname=swarm-manager000000 session=1525226669-Y96023yLhENYOd8EKFcrjzMXKGt7tc0h
OK hostname=swarm-worker000000 session=1525226669-Y96023yLhENYOd8EKFcrjzMXKGt7tc0h
Done requesting diagnostics.
Your diagnostics session ID is 1525226669-Y96023yLhENYOd8EKFcrjzMXKGt7tc0h
Please provide this session ID to the maintainer debugging your issue.

**Comment by Praggie** [comment]
I created swarm with archived template for version 17.06.2 and it worked prefectly. looks like issue with newer version. https://download.docker.com/azure/stable/17.06.2/Docker.tmpl

**Comment by FrenchBen** [comment]
@Praggie Thanks for the issue - I've found the issue and working on a patch. I'll update this issue once it's been fixed.

**Comment by FrenchBen** [comment]
@Praggie a patch has been pushed. let me know if that fixes your problem. I'm going to close this issue for now, but feel free to reopen it if it doesn't solve it.
