### ISSUE TITLE
Persistent disk partition not showing

### ISSUE THREAD

**Issue by semkath** [docker/for-azure#8]
I'm currently experimenting with persistent storage when deploying Docker for Azure. I'm using the docker4azure image. When I attach disks to the VM scale set, I can see the disks in /dev. However, when I create a partition (I tried both fdisk and parted) the newly created partition does not show up in the /dev/ tree. I'm not quite sure why this is. I know that docker4azure is an Alpine Linux image which doesn't have something like udev, but the partition should still appear in the /dev/ tree.
The partition is listed in the dmesg output:

` sdc: sdc1`

But it is not available at /dev/sdc1.

I know that persistent storage with docker4azure is sort of in an experimental state but I simply want to attach some disks and partition them. In my view this should work, but for some reason it isn't.

**Comment by rocketraman** [comment]
+1

@semkath  How did you even attach disks to the vm scale set? I don't see that option in the portal. Did you use a CLI command?

NOTE: there is another use case... I want to backup Docker volume data. The built-in nodes don't have enough room to store the backup temporarily, so if I can attach a larger Azure disk to the nodes in the scale set, I can execute the backup container on each of them, writing the backups to the attached disk.

**Comment by semkath** [comment]
@rocketraman Well the answer to that is.. it's complicated. Azure introduced "managed disks" a couple of weeks ago. Your scale set needs to use managed disks, for more details, see https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks
Unfortunately, the Azure for Docker template does not use managed disks, instead it uses unmanaged disks for the scale sets. This means that I had to basically rewrite the Azure for Docker template to use managed disks. I did other changes as well to suit my deployment needs, but the Azure API documentation provides a way on how to do this.

**Comment by semkath** [comment]
Oh and I figured out why the partition was not showing up, I missed a crucial detail when dealing with managed disks: You have to allow traffic on port 8443. The Azure documentation states as much on https://docs.microsoft.com/en-us/azure/storage/storage-managed-disks-overview but I didn't realize this when I added a network security group to the subnet where my scale set lives.
I will leave this here for posterity so that others can learn from my mistakes.

**Comment by rocketraman** [comment]
@semkath Any chance you can share a diff of your managed disk changes to the template?

**Comment by semkath** [comment]
@rocketraman I have to dig a little into the git history of my changes because I ended up refactoring the template quite heavily to suit my needs. I will try to find a version with minimal changes to the original template file that is provided by docker.
